### ISSUE TITLE
Add author list

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw-blog#25]
Maybe a small marldown file for every possible author with a few words about him/her.

**Comment by mtliendo** [comment]
Would it be preferable for each author to have their own page as opposed to one file that lists them out? 

In the latter approach, we could do something like what I did with [magnoliaJS](https://github.com/jchiatt/magnoliajs.com/blob/master/src/speakerData.js) by keeping speaker data in a json-like file. Thoughts?

**Comment by lipis** [comment]
Yes, maybe an `author.json` file with:

- Name
- Username
- About
- Twitter
- GitHub
- AvatarURL

Where we could add the author's username in the frontmatter of the blogpost.

Also maybe a page template for authors /vjeux, where you could see their posts and links to their Twitter, etc..
