### ISSUE TITLE
Better 404 pages

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw-blog#31]
- https://blog.excalidraw.com/404 ✔
- https://blog.excalidraw.com/asd ✖️

**Comment by j-f1** [comment]
https://zeit.co/docs/configuration#routes/advanced/custom-404

**Comment by lipis** [comment]
Maybe with the gatsby-plugin-now?

**Comment by lipis** [comment]
https://www.gatsbyjs.org/packages/gatsby-plugin-zeit-now/
