### ISSUE TITLE
Videos

### ISSUE THREAD

**Issue by mtliendo** [excalidraw/excalidraw-blog#47]
I'm trying to put out more video content these days.

Would there be value in my showcasing excalidraw's features and if so, what would you all like to see?

**Comment by lipis** [comment]
I think for now Twitter is the best for random videos.. not sure about having them on the blog..

**Comment by dwelle** [comment]
Is it really random videos, or video tutorials? If the latter then I don't see a problem of it being on the blog, esp. if it's part of a post (a youtube embed).

**Comment by mtliendo** [comment]
Yea, sorry late night issue creations never get explained well 😅. 

It was more tutorial work. Similar to what [I did on YouTube](https://youtu.be/JvDmJybANCQ) but perhaps a bit more guided in depth. 

Just throwing around the idea though.

**Comment by lipis** [comment]
Yeah as part of a post would make more sense..! That was an awesome video btw.. I've seen it the first time you posted it.. We came full circle now :)

**Comment by dwelle** [comment]
Even if, nothing wrong with a bit of self-promotion on an OSS you contribute to. Besides, it's awesome :).
