### ISSUE TITLE
Add dark mode

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw-blog#5]
Like in Dan's https://overreacted.io/

**Comment by j-f1** [comment]
`prefers-color-scheme` is [pretty widely supported](https://caniuse.com/#feat=prefers-color-scheme) so we could avoid the whole thing with the switch and just read the system preference.

**Comment by lipis** [comment]
We can start with that, and add the switch later.. I'm sure there will be people asking for it.

**Comment by mtliendo** [comment]
I can get dark mode PR with Dan's implementation up tonight if this is up for grabs?

**Comment by lipis** [comment]
Sure!

**Comment by mtliendo** [comment]
Awesome!

First pass is done with a simple checkbox that adds a class for styling. I wish I could take credit for this, but someone already took Dan's implementation and [made a gatsby plugin](https://www.gatsbyjs.org/packages/gatsby-plugin-dark-mode/). 

I just need to know what colors you were wanting to use.

![excalidraw-themeing](https://user-images.githubusercontent.com/5106417/77242832-d9394480-6bd0-11ea-920f-121b75ec4495.gif)
