### ISSUE TITLE
how to share key?

### ISSUE THREAD

**Issue by happysenior** [excalidraw/excalidraw-blog#550]
https://blog.excalidraw.com/end-to-end-encryption/

I think it is a good resource to know EXCALIDRAW, and its e2e encryption.

But I'm still curious how users share the URL that contains a key they generated?
https://excalidraw.com/?scene=1234#key=BQ1moYESmTEXgtA1KozyVw

Will they share the URL via email? @vjeux 
I think server should not know the entire URL since it contains a key.

**Comment by dwelle** [comment]
You can share the url in any way. The easiest would be a messaging app.

The server doesn't see anything that's after the `#` which includes the key. Only the part of the url before `#` is transmitted to the server, which is why we're not search params for this (`?`).
